# Generated by Django 4.2.1 on 2023-08-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
