# Generated by Django 4.2.1 on 2023-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cartorder_price_alter_cartorderitems_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
