# Generated by Django 4.2.1 on 2023-06-26 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(default='category-icon.png', upload_to='category', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp', 'jpeg', 'svg'])]),
        ),
    ]
