# Generated by Django 4.2.1 on 2023-06-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.CharField(default=50, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='mfd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.IntegerField(default=10, max_length=10),
        ),
    ]
