# Generated by Django 4.2.1 on 2023-07-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(default='a', null=True),
        ),
    ]
