# Generated by Django 4.2.1 on 2023-07-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='name',
        ),
    ]
