# Generated by Django 4.2.1 on 2023-07-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title2',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
