# Generated by Django 4.2.1 on 2023-07-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_title2_category_title3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title3',
        ),
    ]
