# Generated by Django 4.2.1 on 2023-07-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_category_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
