# Generated by Django 4.2.1 on 2023-07-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_category_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
