# Generated by Django 4.2.1 on 2023-07-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_category_title_category_title_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='title_unique',
        ),
    ]
