# Generated by Django 4.2.1 on 2023-07-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_rename_cart_id_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name_plural': 'Cart Items'},
        ),
    ]
