# Generated by Django 4.2.1 on 2023-07-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_cart_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='cart_id',
        ),
    ]
