# Generated by Django 4.2.1 on 2023-07-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_address_line2_alter_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='line2',
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
