# Generated by Django 4.2.1 on 2023-07-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_cartorderitems_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'Cod'), ('online', 'Online')], default='cod', max_length=30),
        ),
    ]
