# Generated by Django 4.2.1 on 2023-07-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_cartorder_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('line1', models.TextField(blank=True, default=None, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('type', models.CharField(choices=[('home', 'Home'), ('office', 'Office')], default='home', max_length=10)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cartorder')),
            ],
        ),
    ]
