# Generated by Django 4.2.1 on 2023-07-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_orderaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='orderaddress',
            options={'verbose_name_plural': 'Order Addresses'},
        ),
    ]
