# Generated by Django 4.2.1 on 2023-07-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_cartorderitems_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
