# Generated by Django 4.2.1 on 2023-07-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_cartorderitems_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='item',
            new_name='product',
        ),
    ]
