# Generated by Django 4.2.1 on 2023-07-19 07:01

import core.models
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_product_featured_alter_product_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('color', 'Color'), ('image', 'Image')], default='text', max_length=10)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varient_category', to='core.category')),
            ],
            options={
                'verbose_name_plural': 'Varients',
            },
        ),
        migrations.CreateModel(
            name='VarientValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('color_code', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('image', models.ImageField(default=None, upload_to='varient-images')),
                ('varient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varient', to='core.varient')),
            ],
            options={
                'verbose_name_plural': 'Varient Values',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(default='product-icon.png', upload_to=core.models.user_directory_path)),
                ('stock_count', models.IntegerField(default=10)),
                ('product_status', models.CharField(choices=[('draft', 'Draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published')], default='published', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=5, max_length=10, prefix='sku', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
