# Generated by Django 4.2.1 on 2023-07-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_productitem_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100),
        ),
        migrations.AddField(
            model_name='productitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100),
        ),
    ]
