# Generated by Django 4.2.1 on 2023-07-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_productitem_discount_price_productitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
