# Generated by Django 4.2.1 on 2023-07-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_product_discount_price_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_count',
        ),
    ]
