# Generated by Django 4.2.1 on 2023-07-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_product_in_stock_remove_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
