# Generated by Django 4.2.1 on 2023-07-19 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_productitem_piid_alter_productitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVarientConfigeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productitem')),
                ('varient_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.varientvalue')),
            ],
        ),
    ]
