# Generated by Django 4.2.1 on 2023-07-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_productvarientconfigeration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvarientconfigeration',
            options={'verbose_name_plural': 'Product Varient Configerations'},
        ),
    ]
