# Generated by Django 4.2.1 on 2023-07-20 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_productitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product-icon.png', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='image',
            field=models.ImageField(default='product-icon.png', upload_to='products'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.product'),
        ),
    ]
