# Generated by Django 4.2.1 on 2023-07-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_product_image_alter_productitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varientvalue',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='varient-images'),
        ),
    ]
