# Generated by Django 4.2.1 on 2023-07-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_productvarientconfigeration_product_varient_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarientconfigeration',
            name='product_varient_link',
        ),
    ]
