# Generated by Django 4.2.1 on 2023-07-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_product_discount_price_product_in_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('variation_category', models.CharField(choices=[('color', 'Color'), ('size', 'Size')], max_length=100)),
                ('variation_value', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_vatiations', to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Variations',
            },
        ),
    ]
