# Generated by Django 4.2.1 on 2023-07-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_cartitem_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={},
        ),
    ]
