# Generated by Django 4.2.1 on 2023-07-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_variation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name_plural': 'Variations'},
        ),
    ]
