# Generated by Django 4.2.1 on 2023-07-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_remove_cartorderitems_variation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
