# Generated by Django 4.2.1 on 2023-07-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_cartorder_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payment'),
        ),
    ]
