# Generated by Django 4.2.1 on 2023-07-28 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_ordercancellationreason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercancellation',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='core.cartorderitems'),
        ),
    ]
