# Generated by Django 4.2.1 on 2023-07-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_alter_cartorder_coupon_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='coupon_discount',
        ),
    ]
