# Generated by Django 4.2.1 on 2023-07-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_alter_cartorder_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='coupon_discount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
