# Generated by Django 4.2.1 on 2023-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_alter_cartorder_coupon_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='whishlist',
            name='products',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
