# Generated by Django 4.2.1 on 2023-07-29 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_alter_offer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category'),
        ),
    ]
