# Generated by Django 4.2.1 on 2023-08-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_alter_offer_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarientlink',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvarientlink',
            name='varient',
        ),
        migrations.RemoveField(
            model_name='varient',
            name='category',
        ),
        migrations.RemoveField(
            model_name='varientvalue',
            name='varient',
        ),
        migrations.DeleteModel(
            name='ProductVarientConfigeration',
        ),
        migrations.DeleteModel(
            name='ProductVarientLink',
        ),
        migrations.DeleteModel(
            name='Varient',
        ),
        migrations.DeleteModel(
            name='VarientValue',
        ),
    ]
