# Generated by Django 4.2.1 on 2023-08-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_remove_productvarientlink_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100),
        ),
    ]
