# Generated by Django 4.2.1 on 2023-08-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_variation_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='stock_count',
            field=models.IntegerField(default=10),
        ),
    ]
