# Generated by Django 4.2.1 on 2023-08-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_variation_stock_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='mrp_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
    ]
