# Generated by Django 4.2.1 on 2023-08-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_variation_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='is_default',
        ),
    ]
