# Generated by Django 4.2.1 on 2023-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_wallet_alter_category_title_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
