# Generated by Django 4.2.1 on 2023-08-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
