# Generated by Django 4.2.1 on 2023-06-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pid',
        ),
    ]
