# Generated by Django 4.2.1 on 2023-07-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_category_title2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title2',
            new_name='title3',
        ),
    ]
