# Generated by Django 4.2.1 on 2023-07-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_title2_maincategory_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategory',
            name='desc',
        ),
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
