# Generated by Django 4.2.1 on 2023-07-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_cartitems_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
