# Generated by Django 4.2.1 on 2023-07-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
    ]
