# Generated by Django 4.2.1 on 2023-07-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_cart_cartitem_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
