# Generated by Django 4.2.1 on 2023-07-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_address_date_alter_address_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='date',
        ),
    ]
