# Generated by Django 4.2.1 on 2023-07-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_orderaddress_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.cartorder'),
        ),
    ]
