# Generated by Django 4.2.1 on 2023-07-12 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_rename_item_cartorderitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('deliverd', 'Delivered')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('deliverd', 'Delivered')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cartorder'),
        ),
    ]
