# Generated by Django 4.2.1 on 2023-07-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_productitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='user',
        ),
    ]
