# Generated by Django 4.2.1 on 2023-07-19 11:11

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_remove_productitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='piid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='core.product'),
        ),
    ]
