# Generated by Django 4.2.1 on 2023-07-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_productvarientlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarientconfigeration',
            name='product_varient_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varient_values', to='core.productvarientlink'),
        ),
        migrations.AlterField(
            model_name='productvarientconfigeration',
            name='product_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prd_varient_values', to='core.productitem'),
        ),
        migrations.AlterField(
            model_name='productvarientlink',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prd_varient', to='core.product'),
        ),
    ]
