# Generated by Django 4.2.1 on 2023-07-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_coupon_cartorder_coupon_discount_cart_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=100),
        ),
    ]
