# Generated by Django 4.2.1 on 2023-07-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_remove_whishlist_product_whishlist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whishlist',
            name='products',
        ),
        migrations.AddField(
            model_name='whishlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product'),
        ),
    ]
